version: '3.5'

services:

  loan:
    container_name: demo_flask_apscheduler
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app-run
    ports:
      - "8080:5003"
    networks:
      - localnet

networks:
  localnet:
    external: true
